"""add_featured_coupon_oauth_mfa_and_order_tax_fields

Revision ID: fd512d6b4e84
Revises: 68bc820f45b9
Create Date: 2026-09-17 13:43:16.817957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd512d6b4e84'
down_revision: Union[str, None] = '68bc820f45b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('orders', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('orders', sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('orders', sa.Column('cgst_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('orders', sa.Column('sgst_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('orders', sa.Column('igst_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('orders', sa.Column('shipping_charge', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('orders', sa.Column('accepted_terms', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('orders', sa.Column('accepted_terms_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_subject', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mfa_recovery_code_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mfa_recovery_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_recovery_code_expires_at')
    op.drop_column('users', 'mfa_recovery_code_hash')
    op.drop_column('users', 'oauth_subject')
    op.drop_column('users', 'oauth_provider')
    op.drop_column('orders', 'accepted_terms_at')
    op.drop_column('orders', 'accepted_terms')
    op.drop_column('orders', 'shipping_charge')
    op.drop_column('orders', 'igst_amount')
    op.drop_column('orders', 'sgst_amount')
    op.drop_column('orders', 'cgst_amount')
    op.drop_column('orders', 'tax_amount')
    op.drop_column('orders', 'subtotal')
    op.drop_column('coupons', 'is_featured')
    # ### end Alembic commands ###
